# Generated by Django 2.2.1 on 2019-05-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pc_model', models.CharField(max_length=30)),
                ('IP_address', models.CharField(max_length=30)),
                ('MAC_address', models.CharField(max_length=30)),
                ('users_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=40)),
                ('ups', models.CharField(max_length=3)),
                ('condition', models.CharField(max_length=10)),
                ('network_connection', models.CharField(max_length=30)),
                ('no_of_network_points', models.CharField(max_length=30)),
            ],
        ),
    ]
