# Generated by Django 2.2.1 on 2019-05-22 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgtapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_or_office', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('printer_or_copier_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=40)),
                ('shared', models.CharField(max_length=3)),
                ('condition', models.CharField(max_length=10)),
                ('toner', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Wireless_Connection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_or_office', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('connection_model', models.CharField(max_length=30)),
                ('serial_number', models.CharField(max_length=40)),
                ('condition', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='MAC_address',
            new_name='MAC_Address',
        ),
        migrations.RenameField(
            model_name='computer',
            old_name='network_connection',
            new_name='staff_or_office',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='condition',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='no_of_network_points',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='ups',
        ),
        migrations.RemoveField(
            model_name='computer',
            name='users_name',
        ),
        migrations.AlterField(
            model_name='computer',
            name='pc_model',
            field=models.CharField(max_length=20),
        ),
    ]
