# Generated by Django 2.2.1 on 2019-05-22 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventorymgtapp', '0002_auto_20190522_1524'),
    ]

    operations = [
        migrations.RenameField(
            model_name='computer',
            old_name='IP_address',
            new_name='IP_Address',
        ),
        migrations.AddField(
            model_name='computer',
            name='condition',
            field=models.CharField(default='Working', max_length=10),
        ),
        migrations.AddField(
            model_name='computer',
            name='network_connection',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='computer',
            name='no_of_network_field',
            field=models.CharField(default='None', max_length=10),
        ),
        migrations.AddField(
            model_name='computer',
            name='serial_number',
            field=models.CharField(default='None', max_length=30),
        ),
        migrations.AddField(
            model_name='computer',
            name='ups',
            field=models.CharField(default='No', max_length=3),
        ),
    ]
